Fix request sending on permissions change
smartdevicelink/sdl_javascript_suite pull request #319
Opened 2020-09-21 20:37 UTC by AKalinich-Luxoft

Fixes #[issue number]

This PR **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Will be tested manually

### Summary
Logic of sending AddCommand and SubscribeButton for sample WEB_VIEW application were moved from OnHmiStatus callback to permissions change callback. This is more reliable way to trigger sending of initial RPCs as changing of HMI level is not always guarantees that RPC is allowed. Also, this is a more simple way to execute some blocks of code just once.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

2020-09-22 16:09 UTC, AKalinich-Luxoft commented
@theresalech Please notice that this PR is ready for Livio review.

2020-10-02 11:57 UTC, crokita commented
@VjKlepikov This PR seems to try to fix more than what the issues it references suggest. I see changes regarding how to subscribe to the buttons to resolve #323. I believe this change is fixing the wrong issue: I have posted a comment on #323 with further details, and what the changes should likely be instead. 

For changing the logic to use permission changes instead of the HMI status, the PR assumes that policies are used in Core, which isn't required. So, there's a scenario where that logic may never run, as opposed to listening for the OnHMIStatus. Additionally, I did not see how that change would help in resolving either of the issues this PR references: if it is meant to help resolve #323 then I believe the comment I gave on that issue is the likely solution. If there is an issue with the main app logic in `_onHmiStatusListener` being run more than once then I request creating an issue that describes how the problem can happen and a separate PR not requiring use of listening to permission changes.

I would be more comfortable approving this PR if it only resolves #321, as I agree with the changes and the issue being accurate.

2020-10-02 18:55 UTC, AKalinich-Luxoft commented
> @VjKlepikov This PR seems to try to fix more than what the issues it references suggest. I see changes regarding how to subscribe to the buttons to resolve #323. I believe this change is fixing the wrong issue: I have posted a comment on #323 with further details, and what the changes should likely be instead.
> 
> For changing the logic to use permission changes instead of the HMI status, the PR assumes that policies are used in Core, which isn't required. So, there's a scenario where that logic may never run, as opposed to listening for the OnHMIStatus. Additionally, I did not see how that change would help in resolving either of the issues this PR references: if it is meant to help resolve #323 then I believe the comment I gave on that issue is the likely solution. If there is an issue with the main app logic in `_onHmiStatusListener` being run more than once then I request creating an issue that describes how the problem can happen and a separate PR not requiring use of listening to permission changes.
> 
> I would be more comfortable approving this PR if it only resolves #321, as I agree with the changes and the issue being accurate.

@crokita let me explain a few things here:
1. I agree with your point that code moved to policy listener may be never run, so I reverted these changes
2. Issue here is more complex than it looks so it make sense to fix it in one PR
3. First issue is that app is trying to subscribe to the same buttons each when it receives `OnHMIStatus`, even if it is already subscribed to it. For example, activate app, deactivate it, and activate again. Or, just click "Show menu" button as suggested in reproduction steps of #323. It can be fixed by adding a new flag. Similar changes was already done for initial AddCommand.
4. Second issue is that `screenManager.addButtonListener` throws the exception if SDL responds with any kind of error. So even if first issue is being fixed and app will make a subscription just once, due to unhandled exception app does not perform subscription to the rest of buttons.
5. Third issue has dependency on second. Because of exception thrown, app does not run the rest of the code, including the code related to sending of AddCommand (issue #321). So fixing of the second issue automatically solves the third issue. This is also a reason why these two issues can't be separated.
6. I also see that app is trying to subscribe to RC buttons, however it is not an RC application according to app manifest. That means that this app will never have a success with it. By that reason, RC buttons was replaced with the regular buttons. Please let me know if you agree with that?

PR has been simplified and a new changes were introduced in https://github.com/smartdevicelink/sdl_javascript_suite/pull/319/commits/c331dec93be0026ae956f70c75dba30c15d427cf

2020-10-02 20:13 UTC, crokita commented
@AKalinich-Luxoft I see the issue regarding the app executing its main logic multiple times. The buttons get subscribed to multiple times when closing the application and re-activating it. I think the changes made to this PR make sense now. 

I think it's fine for point 6. for the WebEngine app to subscribe to those buttons because the app type is not remote control as you've mentioned. Furthermore, the issues found here will apply to the other example apps in this project, regarding over subscription of buttons and not catching for subscription errors. Can you apply the fixes to the `node/hello-sdl`, `node/hello-sdl-tcp` and `js/hello-sdl` example apps as well?

2020-10-02 23:34 UTC, AKalinich-Luxoft commented
> @AKalinich-Luxoft I see the issue regarding the app executing its main logic multiple times. The buttons get subscribed to multiple times when closing the application and re-activating it. I think the changes made to this PR make sense now.
> 
> I think it's fine for point 6. for the WebEngine app to subscribe to those buttons because the app type is not remote control as you've mentioned. Furthermore, the issues found here will apply to the other example apps in this project, regarding over subscription of buttons and not catching for subscription errors. Can you apply the fixes to the `node/hello-sdl`, `node/hello-sdl-tcp` and `js/hello-sdl` example apps as well?

@crokita It's a good idea to apply the same changes to other example apps.
Done in https://github.com/smartdevicelink/sdl_javascript_suite/pull/319/commits/8e2747e2a8a851d500cfba1de3cf33a5a9ab299d
Please double check if it works as expected now.

2020-10-05 14:49 UTC, crokita requested changes
See feedback @AKalinich-Luxoft

2020-10-05 15:10 UTC, AKalinich-Luxoft commented on examples/js/hello-sdl/index.html
> +                        const screenManager = this._sdlManager.getScreenManager();
@crokita good catch!
Last commit has been amended - https://github.com/smartdevicelink/sdl_javascript_suite/pull/319/commits/f8c40df5daf59b6fcc70eecd6e66eefb8b3f4b26

2020-10-05 19:17 UTC, crokita approved these changes

2020-10-05 19:17 UTC, merged