Add new API to SetMediaClockTimer
smartdevicelink/sdl_javascript_suite pull request #356
Opened 2020-12-04 20:36 UTC by crokita

Fixes #346 

This PR is ready for review. The equivalent RPC spec PR should be approved before this PR should be merged: https://github.com/smartdevicelink/rpc_spec/pull/292

### Risk
This PR makes minor API changes.

### Summary
Updates SetMediaClockTimer to include backSeekIndicator and forwardSeekIndicator.

2021-01-19 19:06 UTC, renonick87 reviewed
This PR is missing the SeekStreamingIndicator and SeekIndicatorType RPC files.

2021-01-19 19:08 UTC, renonick87 requested changes
See comment above regarding missing files.

2021-01-20 14:52 UTC, crokita commented
Added missing files

2021-01-22 21:26 UTC, renonick87 approved these changes

2021-01-27 21:08 UTC, merged