[SDL-0238] Keyboard Enhancements
smartdevicelink/sdl_javascript_suite pull request #366
Opened 2020-12-14 16:14 UTC by ymalovanyi

Fixes #340

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [N/A] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
All new structs and enums, as well as enhanced ones, are covered with unit tests.

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Applied [[SDL-0238] Keyboard Enhancements](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0238-Keyboard-Enhancements.md) changes

### Changelog
##### Breaking Changes
N/A

##### Enhancements
* Added required getters/setters in related RPC classes

##### Bug Fixes
N/A

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-12-14 16:18 UTC, ymalovanyi commented
@santhanamk the PR is ready for Ford review.

2020-12-15 02:22 UTC, santhanamk approved these changes
@ymalovanyi Code looks good.

2020-12-18 17:10 UTC, jordynmackool commented
@ymalovanyi is this ready for Livio Reivew?

2020-12-18 17:42 UTC, vladmu commented
@jordynmackool @crokita the description was fixed to include all sections from the template and the code was tested against the Core and HMI (corresponded links also included in the description). Please review. Also, please take into account that the JavaScript Suite doesn't contain Choice Set Manager (it seems it will be added in the implementation of https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0272-sdl-javascript-manager-layer.md) therefore only RPC changes of the proposal included here and we have tested this against Core with cases defined in the description.

2021-02-03 21:47 UTC, jordynmackool commented
@ymalovanyi / @vladmu the proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [Revise SDL-0238 Keyboard Enhancements](https://github.com/smartdevicelink/sdl_evolution/pull/1119).

Please make the needed updates to this PR and then tag @renonick87 to review when ready. Thanks!

2021-02-08 15:33 UTC, BogMW commented
@renonick87 all required adjustments were made, the PR is ready for review.

2021-02-09 21:32 UTC, renonick87 requested changes
@ymalovanyi  From an initial review, the content of this PR looks good. But with the addition of the ChoiceSetManager in https://github.com/smartdevicelink/sdl_javascript_suite/pull/371, there are additional updates needed for the manager to support this feature.

2021-02-18 12:48 UTC, vladmu commented
@renonick87, we've made additional changes to the ChoiceSetManager. Moreover, this aligned with the last state of Java PR https://github.com/smartdevicelink/sdl_java_suite/pull/1587. We have tested the code with the Core/HMI. Please review.

2021-02-22 21:21 UTC, renonick87 reviewed
@ymalovanyi See my feedback for a minor suggestion.

2021-02-22 21:21 UTC, renonick87 commented on lib/js/src/manager/screen/choiceset/_PresentChoiceSetOperation.js
> +            } else if (onKeyboardInput.getEvent().equals(KeyboardEvent.INPUT_KEY_MASK_ENABLED) || onKeyboardInput.getEvent().equals(KeyboardEvent.INPUT_KEY_MASK_DISABLED)) {
This addition should also be included in the _PresentKeyboardOperation.js file.

2021-02-23 13:38 UTC, BogMW commented
Hey @renonick87 , changes were added.

2021-02-24 20:46 UTC, renonick87 approved these changes

2021-02-24 20:59 UTC, merged