Fix manager to not delete and set identical voice commands
smartdevicelink/sdl_javascript_suite pull request #438
Opened 2021-05-19 21:26 UTC by renonick87

Fixes #433 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have verified that this PR passes lint validation
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit tests to verify that VoiceCommands are added/deleted correctly.

### Changelog
##### Bug Fixes
* The VoiceCommandManager will no longer delete a VoiceCommand if the VoiceCommand is going to be immediately added again as part of the same update operation. Below is sample code that can be used to test the functionality. Option 1-3 will be added as part of the first operation. The second operation will delete Option 3 and add Option 4 while leaving Option 1/2 untouched.
```
const voiceCommands = [
    new SDL.manager.screen.utils.VoiceCommand(['Option 1'], () => {}),
    new SDL.manager.screen.utils.VoiceCommand(['Option 2'], () => {}),
    new SDL.manager.screen.utils.VoiceCommand(['Option 3'], () => {}),
];

await screenManager.setVoiceCommands(voiceCommands);
const newVoiceCommands = [
    voiceCommands[0],
    voiceCommands[1],
    new SDL.manager.screen.utils.VoiceCommand(['Option 4'], () => {}),
]
await screenManager.setVoiceCommands(newVoiceCommands);
```

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-05-20 21:00 UTC, crokita reviewed
See minor feedback

2021-05-20 21:00 UTC, crokita commented on lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js
> +    _setOldVoiceCommands (oldVoiceCommands) {
This doesn't look like it's used anywhere

2021-05-21 15:26 UTC, crokita approved these changes

2021-05-27 20:21 UTC, renonick87 commented
Updates made since last review:
- Equality check on voice commands is not done at the start.
- Added a clone method to the VoiceCommand class and unit tests to cover it.
- The manager's _voiceCommands is set to null if the commands are invalid.
- Updated the docs description for getVoiceCommands since it says that it returns the currently set voice commands but does not actually return _currentVoiceCommands.
- Reduced the logic in _voiceCommandsNotInSecondArray to be much cleaner.
- Fixed the case where updating a Voice Command's listener and calling setVoiceCommands would not update the listener.

2021-06-01 15:17 UTC, crokita requested changes
See feedback

2021-06-01 15:17 UTC, crokita commented on lib/js/src/manager/screen/utils/_VoiceCommandUpdateOperation.js
> +            return secondArray;
Elements from the second array should not be in the result according to the docs. Should return `[]` in this case
```suggestion
            return [];
```

2021-06-01 18:31 UTC, crokita approved these changes

2021-06-02 17:14 UTC, merged