Fix T&G issues with updating state rapidly
smartdevicelink/sdl_javascript_suite pull request #555
Opened 2022-09-16 15:53 UTC by crokita

Fixes #554 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Add tests for the new _updateTargetStateWithErrorState method

### Summary
When sending updates of invalid data followed by valid data to the T&G manager, the valid data will not be thrown out with the invalid data.

##### Bug Fixes
Resolved an issue with _updatePendingOperationsWithNewScreenData where the wrong identifier was used in the for loop for looping over tasks.

Also fixed _TextAndGraphicUpdateOperation to properly await on sending shows so that the task does not immediately complete.

Fixed variables in test returning undefined due to non-existent SDL.rpc.enums.MetadataType.MEDIA_TITLE value.

2022-09-19 15:21 UTC, theresalech commented
@renonick87 while reviewing, please verify that this check is in place: https://github.com/smartdevicelink/sdl_ios/pull/2107/commits/8180e65affca9258425cef1f016b36768c18c288

2022-09-20 20:13 UTC, renonick87 requested changes

2022-09-20 20:43 UTC, JulianKast commented on lib/js/src/manager/screen/_TextAndGraphicManagerBase.js
>      _sdlUpdate (supersedePreviousOperations, listener) {
supersedePreviousOperations is not used anymore

2022-09-20 20:44 UTC, JulianKast commented on lib/js/src/manager/screen/_TextAndGraphicManagerBase.js
>          this._currentOperationListener = listener;
You should be able to get rid of `_currentOperationListener`

2022-09-21 18:48 UTC, renonick87 approved these changes

2022-09-22 14:39 UTC, merged