Apply fix to alert icon not uploading
smartdevicelink/sdl_javascript_suite pull request #561
Opened 2022-09-21 21:13 UTC by crokita

Fixes #558 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Tests the Alert RPC generation when an AlertView has an icon

### Summary
_PresentAlertOperation now keeps track of uploaded artwork names and uses it to check whether to attach the AlertView icon to the Alert RPC.

2022-09-22 14:05 UTC, crokita commented
Note: artworksToBeUploaded line addition needs to filter out failed image uploads first before being used

2022-09-23 15:58 UTC, renonick87 requested changes

2022-09-23 15:58 UTC, renonick87 commented on lib/js/src/manager/screen/utils/_PresentAlertOperation.js
> +            const artworkNamesSuccessfullyUploaded = artworkResults.filter(result => result.success).map(result => result.artwork.getName());
It seems odd to me here that we have a loop to build `artworkResults` into an array of JSON objects only for it to be filtered and torn down immediately after. 
We should be able to condense this to one loop that simply checks the success result, then only pushes the artwork name to the array when `success=true`.
```suggestion
            const artworkNamesSuccessfullyUploaded = [];
            for (let index = 0; index < successes.length; index++) {
            // only keep artworks that have been uploaded successfully by the file manager
                if (successes[index]) {
                    artworkNamesSuccessfullyUploaded.push(artworksToBeUploaded[index].getName());
                }
            }
```

2022-09-23 18:33 UTC, renonick87 approved these changes

2022-09-23 18:36 UTC, merged